/*
        @Author: Sergio Migueis - K2
        @Description: Test Class for the NewOpportunityLWC Use Cases
        @TestClasses:
            -NewOpportunityController
            -DTOUtils
            -DAOMetadado

        @History:
        05/11/2019 - Creation.
        20/11/2019 - Connection with backend.
        26/11/2019 - Deploy from scratchorg
 */
@isTest
public class TestNewOpportunityController {
    
}